name: eddie_the_dev_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  url_launcher:
  intl: 
  firebase_core: 
  cloud_firestore: 
  http: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Adieu
      fonts:
        - asset: assets/fonts/Adieu-Regular.otf
          weight: 600
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 900