// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdj98i07v61UJ5fhlRZ7VYds_4scqXGq4',
    appId: '1:33859425635:web:0256ec3325501681406f56',
    messagingSenderId: '33859425635',
    projectId: 'eddie-the-dev',
    authDomain: 'eddie-the-dev.firebaseapp.com',
    storageBucket: 'eddie-the-dev.firebasestorage.app',
    measurementId: 'G-T7JX6YDMZP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD93FbfmtRHCBzsIC3iwx2713xSWLaurMk',
    appId: '1:33859425635:ios:a5eb47fc0aeb5597406f56',
    messagingSenderId: '33859425635',
    projectId: 'eddie-the-dev',
    storageBucket: 'eddie-the-dev.firebasestorage.app',
    iosBundleId: 'com.example.eddieTheDevFrontend',
  );

}